server:
  port: 80

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hesher?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 123
    username: admin
    password: MetalFans@1997
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
mybatis:
  config-location: classpath:mapper/config/mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.Hesher.pojo
