server:
  port: 8080

spring:  thymeleaf:    cache: false
    prefix: classpath:/templates/
  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hesher?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
  mvc:    static-path-pattern: /**
 
mybatis:  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.Hesher.pojo